const drugDatabase = [ // for getQuantity()
    {
        drug: "Accrufer capsule",
        quantity: "30/30",
        diagnosis: "iron deficiency anemia", 
        formulary: false, 
    },  
    {
        drug: "adapalene-benzoyl peroxide gel",
        quantity: "45/30",
        diagnosis: "acne vulgaris", 
        formulary: false, 
    },  
    {
        drug: "Adderall tablet",
        quantity: "30/30",
        diagnosis: "ADHD", 
        formulary: false, 
    },  
    {
        drug: "Adderall XR capsule",
        quantity: "30/30",
        diagnosis: "ADHD", 
        formulary: false, 
    },  
    {
        drug: "Aimovig pen",
        quantity: "1/25",
        diagnosis: "migraine prophylaxis", 
    },  
    {
        drug: "Airsupra inhaler",
        quantity: "10.7/30 (120 inhalations per inhaler)",
        diagnosis: "bronchospasm", 
        formulary: false, 
    },  
    {
        drug: "Ajovy pen",
        quantity: "1.5/30",
        diagnosis: "migraine prophylaxis", 
        formulary: false, 
    },  
    {
        drug: "Aklief cream",
        quantity: "45/30",
        diagnosis: "acne vulgaris", 
        formulary: false, 
    },  
    {
        drug: "alprazolam tablet",
        quantity: "180/30",
        diagnosis: "anxiety", 
        quantityLimitCriteria: true, 
    },  
    {
        drug: "Anzupgo cream",
        quantity: "30/30",
        diagnosis: "atopic dermatitis", 
        altDiagnosis: "chronic hand eczema",
        formulary: false, 
    },  
    {
        drug: "Arazlo lotion",
        quantity: "45/30",
        diagnosis: "acne vulgaris", 
        formulary: false, 
    },  
    {
        drug: "armodafinil tablet",
        quantity: "30/30",
        diagnosis: "narcolepsy", 
        altDiagnosis: "hypersomnia",
    },  
    {
        drug: "Austedo capsule",
        quantity: "30/30",
        diagnosis: "tardive dyskinesia", 
        specialty: true,
    }, 
    {
        drug: "Auvelity tablet",
        quantity: "60/30",
        diagnosis: "major depressive disorder", 
    },  
    {
        drug: "azelaic acid gel",
        quantity: "50/30",
        diagnosis: "rosacea", 
        altDiagnosis: "acne vulgaris",
    },  
    {
        drug: "Azstarys capsule",
        quantity: "30/30",
        diagnosis: "ADHD", 
        formulary: false,
    },  
    {
        drug: "Baqsimi nasal spray",
        quantity: "1/30",
        diagnosis: "T2DM",
        formulary: false, 
    },  
    {
        drug: "Belsomra tablet",
        quantity: "30/30",
        diagnosis: "insomnia", 
    },  
    {
        drug: "bismuth-metronidazole-tetracycline capsule",
        quantity: "120/10",
        diagnosis: "H. pylori infection",
        altDiagnosis: "GERD", 
        formulary: false,
    },  
    {
        drug: "brivaracetam tablet",
        quantity: "60/30",
        diagnosis: "epilepsy",
        altDiagnosis: "seizures", 
    },  
    {
        drug: "budesonide EC 3 mg capsule",
        quantity: "120/10",
        diagnosis: "Crohn's disease",
        altDiagnosis: "colitis", 
    },  
    {
        drug: "Caplyta capsule",
        quantity: "270/30",
        diagnosis: "bipolar disorder", 
        altDiagnosis: "schizophrenia",
    },  
    {
        drug: "calcipotriene ointment",
        quantity: "60/30",
        diagnosis: "psoriasis vulgaris", 
        altDiagnosis: "acne vulgaris",
        formulary: false,
    },  
    {
        drug: "Cequa solution",
        quantity: "60/30",
        diagnosis: "dry eye syndrome", 
        formulary: false,
    },  
    {
        drug: "cinacalcet tablet",
        quantity: "30/30",
        diagnosis: "hyperparathyroidism", 
        altDiagnosis: "hypercalcemia",
    },  
    {
        drug: "clindamycin-benzoyl peroxide gel",
        quantity: "45/30",
        diagnosis: "acne vulgaris", 
        formulary: false,
    },  
    {
        drug: "clobazam tablet",
        quantity: "30/30",
        diagnosis: "Lennox-Gastaut Syndrome", 
        altDiagnosis: "epilepsy",
    },  
    {
        drug: "clomiphene tablet",
        quantity: "30/30",
        diagnosis: "testicular hypofunction",
        formulary: false, 
    },  
    {
        drug: "Combipatch patch",
        quantity: "8/28",
        diagnosis: "menopausal and female climacteric states",
        formulary: false, 
    },  
    {
        drug: "Creon DR capsule",
        quantity: "300/90",
        diagnosis: "exocrine pancreatic insufficiency", 
        altDiagnosis: "cystic fibrosis",
    },  
    {
        drug: "Cresemba capsule",
        quantity: "30/30",
        diagnosis: "aspergillosis",
        altDiagnosis: "fungal infection prevention during chemotherapy",  
        formulary: false, 
    },  
    {
        drug: "Crexont ER capsule",
        quantity: "60/30",
        diagnosis: "parkinsonism",
        formulary: false, 
    },  
    {
        drug: "cromolyn oral concentrate",
        quantity: "270/30",
        diagnosis: "mastocystitis",
    },  
    {
        drug: "dabigatran capsule",
        quantity: "60/90",
        diagnosis: "atrial fibrillation",
        altDiagnosis: 'deep vein thrombosis',
        formulary: false, 
    },  
    {
        drug: "Dapsone 7.5% gel",
        quantity: "90/90",
        diagnosis: "acne vulgaris", 
    },  
    {
        drug: "Dexcom G6 sensor",
        quantity: "3/30",
        altQuantity: "",
        diagnosis: "T2DM", 
        altDiagnosis: "T1DM", 
    },  
    {
        drug: "Dexcom G6 receiver",
        quantity: "1/30",
        altQuantity: "",
        diagnosis: "T2DM", 
        altDiagnosis: "T1DM", 
    },   
    {
        drug: "Dexcom G6 transmitter",
        quantity: "1/90",
        altQuantity: "",
        diagnosis: "T2DM", 
        altDiagnosis: "T1DM", 
    },   
    {
        drug: "Dexcom G7 receiver",
        quantity: "1/30",
        diagnosis: "T2DM",
        altDiagnosis: "T1DM", 
    }, 
    {
        drug: "Dexcom G7 sensor",
        quantity: "2/30",
        altQuantity: "3/30",
        diagnosis: "T2DM", 
        altDiagnosis: "T1DM", 
    },   
    {
        drug: "dulaglutide pen",
        quantity: "2/28",
        diagnosis: "T2DM", 
    },     
    {
        drug: "duloxetine 40 mg capsule",
        quantity: "30/30",
        diagnosis: "major depressive disorder", 
        formulary: false, 
    },  
    {
        drug: "Durysta implant",
        quantity: "2/30",
        diagnosis: "primary open-angle glaucoma", 
        formulary: false, 
    },  
    {
        drug: "Emgality 100 mg pen",
        quantity: "3/28",
        diagnosis: "migraine prophylaxis", 
    },  
    {
        drug: "Emgality 120 mg pen",
        quantity: "2/28",
        diagnosis: "migraine prophylaxis", 
    },  
    {
        drug: "Emverm chewable tablet",
        quantity: "12/30",
        diagnosis: "roundworm",
        altDiagnosis: "whipworm", 
    },  
    {
        drug: "Eohilia suspension packet",
        quantity: "10/30",
        diagnosis: "eosinophilic esophagitis", 
        formulary: false, 
    },  
    {
        drug: "Eucrisa ointment",
        quantity: "60/30",
        diagnosis: "dermatitis", 
    },  
    {
        drug: "exemestane tablet",
        quantity: "30/30",
        diagnosis: "breast cancer", 
        formulary: false, 
    },  
    {
        drug: "febuxostat tablet",
        quantity: "30/30",
        diagnosis: "gout", 
        altDiagnosis: "tumor lysis syndrome",
    },  
    {
        drug: "fluorometholone eye drops",
        quantity: "5/30",
        diagnosis: "dry eye disease", 
        altDiagnosis: 'keratoconjunctivitis sicca',
        formulary: false, 
    },  
    {
        drug: "fluticasone nasal spray",
        quantity: "16/30",
        diagnosis: "allergic rhinitis", 
        formulary: false, 
    },  
    {
        drug: "Foundayo tablet",
        quantity: "30/30",
        diagnosis: "obesity", 
        formulary: false, 
    },  
    {
        drug: "FreeStyle Libre 3+ sensor",
        quantity: "2/30",
        altQuantity: "3/30",
        diagnosis: "T2DM", 
        altDiagnosis: "T1DM", 
        formulary: false, 
    },  
    {
        drug: "Fycompa tablet",
        quantity: "30/30",
        diagnosis: "partial (focal) seizures", 
        altDiagnosis: "generalized tonic-clonic seizures",
    },  
    {
        drug: "gabapentin 200 mg capsule", 
        quantity: "60/30",
        diagnosis: "radiculopathy", 
        formulary: false, 
    },  
    {
        drug: "Gemtesa tablet", 
        quantity: "30/30",
        diagnosis: "overactive bladder", 
        formulary: false, 
    },  
    {
        drug: "Gvoke HypoPen", 
        quantity: "0.2/30",
        diagnosis: "T2DM",
        altDiagnosis: "T1DM", 
        formulary: false, 
    },  
    {
        drug: "Hemangeol oral solution",
        quantity: "120/30",
        diagnosis: "hemangioma", 
        formulary: false, 
    },  
    {
        drug: "Ibsrela tablet",
        quantity: "60/30",
        diagnosis: "IBS-C", 
        formulary: false, 
    },  
    {
        drug: "icosapent ethyl capsule",
        quantity: "120/30",
        diagnosis: "hyperlipidemia",
    }, 
    {
        drug: "Icotyde tablet", 
        quantity: "30/30",
        diagnosis: "psoriasis vulgaris", 
        formulary: false, 
        specialty: true,
    },  
    {
        drug: "Ingrezza capsule",
        quantity: "30/30",
        diagnosis: "Huntington's disease", 
        altDiagnosis: "tardive dyskinesia",
        formulary: false, 
        specialty: true,
    },  
    {
        drug: "insulin aspart pen",
        quantity: "15/30",
        diagnosis: "T2DM", 
        altDiagnosis: 'T1DM',
        formulary: false, 
    },  
    {
        drug: "insulin glargine pen",
        quantity: "15/30",
        diagnosis: "T2DM", 
        altDiagnosis: 'T1DM',
        formulary: false, 
    },  
    {
        drug: "insulin glargine-yfgn pen",
        quantity: "15/30",
        diagnosis: "T2DM", 
        altDiagnosis: 'T1DM',
        formulary: false, 
    },  
    {
        drug: "insulin lispro pen",
        quantity: "15/30",
        diagnosis: "T2DM", 
        altDiagnosis: 'T1DM',
        formulary: false, 
    },  
    {
        drug: "iron sucrose vial",
        quantity: "50/30",
        diagnosis: "iron deficiency anemia", 
    },  
    {
        drug: "itraconazole capsule",
        quantity: "20/10",
        diagnosis: "aspergillosis",
        altDiagnosis: "histoplasmosis",
    }, 
    {
        drug: "itraconazole solution",
        quantity: "?",
        diagnosis: "esophageal candidiasis",
        altDiagnosis: "oropharyngeal candidiasis",

    }, 
    {
        drug: "ivermectin 1% cream",
        quantity: "45/30",
        diagnosis: "rosacea",
        altDiagnosis: "acne vulgaris",
    }, 
    {
        drug: "Jakafi XR tablet",
        specialty: true,  
    },  
    {
        drug: "Jatenzo capsule",
        quantity: "60/30",
        diagnosis: "testicular hypofunction",
        formulary: false,  
    },  
    {
        drug: "Jentadueto tablet",
        quantity: "30/30",
        diagnosis: "T2DM",
        formulary: false,  
    },  
    {
        drug: "Jornay PM capsule",
        quantity: "30/30",
        diagnosis: "ADHD",
        formulary: false, 
    }, 
    {
        drug: "Journavx tablet",
        quantity: "30/14",
        diagnosis: "acute pain",
        quantityLimitCriteria: true,     
    }, 
    {
        drug: "Jublia topical solution",
        quantity: "4/30",
        diagnosis: "tinea unguium",
        formulary: false, 
    }, 
    {
        drug: "Jynarque tablet",
        quantity: "30/30",
        diagnosis: "CKD",
        formulary: false,
        specialty: true, 
    }, 
    {
        drug: "Kerendia tablet",
        quantity: "30/30",
        diagnosis: "chronic kidney disease",
        altDiagnosis: "heart failure" 
    },
    {
        drug: "lacosamide tablet",
        quantity: "30/30",
        diagnosis: "partial (focal) seizures", 
        altDiagnosis: "generalized tonic-clonic seizures", 
    },   
    {
        drug: "lamotrigine ER tablet",
        quantity: "30/30",
        diagnosis: "seizures", 
        altDiagnosis: "bipolar disorder", 
    }, 
    {
        drug: "Lantus Solostar pen",
        dosageForm: "pen", 
        quantity: "15/30",
        diagnosis: "T2DM", 
        formulary: false, 
    },  
    {
        drug: "levothyroxine capsule",
        quantity: "30/30",
        diagnosis: "hypothyroidism", 
        formulary: false, 
    },  
    {
        drug: "lidocaine 5% patch",
        quantity: "30/30", 
        diagnosis: "low back pain",
        altDiagnosis: "chronic pain",
    }, 
    {
        drug: "liraglutide pen, Saxenda generic",
        quantity: "9/30",
        diagnosis: "obesity",
        formulary: false,
    },
    {
        drug: "liraglutide pen (Victoza)",
        quantity: "9/30",
        diagnosis: "T2DM",
    },
    {
        drug: "lisdexamfetamine capsule",
        quantity: "30/30",
        diagnosis: "ADHD", 
    },  
    {
        drug: "lisdexamfetamine chewable tablet",
        quantity: "30/30",
        diagnosis: "ADHD", 
    },  
    {
        drug: "Lokelma powder packet",
        quantity: "30/30",
        diagnosis: "hyperkalemia",
    }, 
    {
        drug: "lurasidone tablet",
        quantity: "30/30",
        diagnosis: "bipolar disorder",
    }, 
    {
        drug: "Lybalvi tablet",
        quantity: "30/30",
        diagnosis: "bipolar disorder",
        altDiagnosis: "schizophrenia",  
        formulary: false, 
    },  
    {
        drug: "Lynkuet capsule",
        quantity: "60/30",
        diagnosis: "menopausal and female climacteric states",
        altDiagnosis: "flushing",  
        formulary: false, 
    },  
    {
        drug: "Lyumjev KwikPen",
        quantity: "15/30",
        diagnosis: "T1DM",
        altDiagnosis: "T2DM",  
        formulary: false, 
    },  
    {
        drug: "metformin ER 1,000 mg osm-tab", 
        quantity: "60/30",
        diagnosis: "T2DM",
        formulary: false,  
    },  
    {
        drug: "metformin ER 1,000 mg gastr-tab",
        quantity: "60/30",
        diagnosis: "T2DM",
        formulary: false,  
    },  
    {
        drug: "methotrexate vial",
        quantity: "4/30",
        diagnosis: "rheumatoid arthritis",
    }, 
    {
        drug: "mirabegron ER tablet",
        quantity: "30/30",
        diagnosis: "overactive bladder",
        altDiagnosis: 'frequency of micturition',
    }, 
    {
        drug: "Miebo eye drops",
        quantity: "3/30",
        diagnosis: "dry eye syndrome",
    }, 
    {
        drug: "Monoferric vial",
        quantity: "",
        diagnosis: "iron deficiency anemia",
        formulary: false,
    }, 
    {
        drug: "Mounjaro pen",
        quantity: "2/28",
        diagnosis: "T2DM",
    }, 
    {
        drug: "Myfembree tablet",
        quantity: "30/30",
        diagnosis: "endometriosis",
        altDiagnosis: "uterine fibroids",
        formulary: false,
    }, 
    {
        drug: "Natesto nasal spray", 
        quantity: "7.320/30",
        diagnosis: "testicular hypofunction",
        formulary: false,  
    },  
    {
        drug: "Nayzilam nasal spray",
        quantity: "2/30",
        diagnosis: "convulsions",
        altDiagnosis: "seizures",
    }, 
    {
        drug: "Neffy nasal spray",
        quantity: "2/30",
        diagnosis: "anaphylaxis",
    }, 
    {
        drug: "Nexletol tablet",
        quantity: "30/30",
        diagnosis: "hyperlipidemia",
        altDiagnosis: "hypercholesterolemia", 
        formulary: false, 
    }, 
    {
        drug: "Nexlizet tablet",
        quantity: "30/30",
        diagnosis: "hyperlipidemia",
        altDiagnosis: "hypercholesterolemia", 
        formulary: false, 
    }, 
    {
        drug: "Nurtec ODT",
        quantity: "16/30",
        diagnosis: "acute treatment of migraines",
        altDiagnosis: "migraine prophylaxis",
        formulary: false, 
    }, 
    {
        drug: "omega-3 ethyl esters capsule",
        quantity: "120/30",
        diagnosis: "hyperlipidemia", 
        altDiagnosis: "pure hyperglyceridemia",
    },   
    {
        drug: "Omnipod 5 pods",
        quantity: "10/30",
        diagnosis: "T1DM",
    }, 
    {
        drug: "Opzelura cream", 
        quantity: "60/30",
        diagnosis: "atopic dermatitis",
        altDiagnosis: "psoriasis",  
        formulary: false, 
    },  
    {
        drug: "Orilissa tablet", 
        quantity: "60/30",
        diagnosis: "endometriosis",
    },
    {
        drug: "Osphena tablet", 
        quantity: "30/30",
        diagnosis: "menopausal and female climacteric states",
    },
    {
        drug: "Ozempic pen", 
        quantity: "3/28",
        diagnosis: "T2DM",
        altDiagnosis: "obesity",
    },
    {
        drug: "Ozempic tablet",
        quantity: "30/30",
        diagnosis: "T2DM",
        altDiagnosis: "obesity",
    }, 
    {
        drug: "PEG-3350 and electrolytes solution",
        quantity: "4000/1",
        diagnosis: "colonoscopy",
        formulary: false,
    }, 
    {
        drug: "pimecrolimus cream",
        quantity: "30/30",
        diagnosis: "atopic dermatitis",
        altDiagnosis: "perioral dermatitis", 
        formulary: false,
    },
    {
        drug: "posaconazole tablet",
        quantity: "30/30",
        diagnosis: "aspergillosis",
        altDiagnosis: "transplant", 
        formulary: false,
    },
    {
        drug: "Prevymis tablet",
        quantity: "28/28",
        diagnosis: "CMV prevention",
        altDiagnosis: "transplant status", 
        formulary: false,
    },
    {
        drug: "ProAir RespiClick inhaler",
        quantity: "1/30",
        diagnosis: "asthma",
        formulary: false,
    },
    {
        drug: "Qbrexza cloth",
        quantity: "30/30",
        diagnosis: "primary hyperhidrosis",
        formulary: false,
    },
    {
        drug: "Qelbree ER capsule",
        quantity: "30/30",
        diagnosis: "ADHD",
        formulary: false,
    },
    {
        drug: "Qulipta tablet",
        quantity: "30/30",
        diagnosis: "migraine prophylaxis",
    },
    {
        drug: "Quviviq tablet",
        quantity: "30/30",
        diagnosis: "insomnia",
        formulary: false,
    },
    {
        drug: "Relistor tablet", 
        quantity: "30/30",
        diagnosis: "drug-induced constipation",
        altDiagnosis: "opioid-induced constipation",
        formulary: false,
    }, 
    {
        drug: "Restasis eye drops",
        quantity: "60/30",
        diagnosis: "keratoconjunctivitis",
    },
    {
        drug: "Rexulti tablet",
        quantity: "60/30",
        diagnosis: "major depressive disorder",
        altDiagnosis: "schizophrenia",
    },
    {
        drug: "Rhofade cream", 
        quantity: "30/30",
        diagnosis: "rosacea",
        formulary: false,
    }, 
    {
        drug: "Rhopressa eye drops", 
        quantity: "2.5/30",
        diagnosis: "glaucoma",
        formulary: false,
    }, 
    {
        drug: "rivastigmine capsule", 
        quantity: "60/30",
        diagnosis: "dementia",
        altDiagnosis: "memory loss",
    }, 
    {
        drug: "roflumilast tablet", 
        quantity: "30/30",
        diagnosis: "asthma",
    }, 
    {
        drug: "Rybelsus tablet", 
        quantity: "30/30",
        diagnosis: "T2DM",
        altDiagnosis: "obesity",
    }, 
    {
        drug: "Santyl ointment", 
        quantity: "30/30",
        diagnosis: "ulcer",
        altDiagnosis: "burn",
    }, 
    {
        drug: "sitagliptin tablet", 
        quantity: "30/30",
        diagnosis: "T2DM",
        formulary: false,
    }, 
    {
        drug: "Spravato dose pack", 
        quantity: "8/14",
        diagnosis: "major depressive disorder",
        formulary: false,
    }, 
    {
        drug: "Sucraid solution", 
        quantity: "360/30",
        diagnosis: "sucrase-isomaltase deficiency",
        formulary: false,
    }, 
    {
        drug: "sucralfate oral suspension", 
        quantity: "300/30",
        diagnosis: "GERD",
        altDiagnosis: "canker sore",
        formulary: false,
    }, 
    {
        drug: "Sunosi tablet", 
        quantity: "30/30",
        diagnosis: "narcolepsy",
        altDiagnosis: "OSA",
    }, 
    {
        drug: "Synjardy XR tablet", 
        quantity: "180/90",
        diagnosis: "T2DM",
        quantityLimitCriteria: true,
    }, 
    {
        drug: "tadalafil 5 mg tablet", 
        quantity: "30/30", 
        diagnosis: "male erectile dysfunction", 
        altDiagnosis: "benign prostatic hyperplasia",
    }, 
    {
        drug: "tadalafil 10 mg tablet", 
        quantity: "30/30", 
        diagnosis: "male erectile dysfunction", 
        formulary: false, 
    }, 
    {
        drug: "Talicia DR capsule", 
        quantity: "168/14", 
        diagnosis: "H. pylori infection",
        altDiagnosis: "GERD",  
        formulary: false, 
    }, 
    {
        drug: "tazarotene cream",
        quantity: "60/30",
        altQuantity: "60/30",
        diagnosis: "acne vulgaris",
        altDiagnosis: "plaque psoriasis",
    }, 
    {
        drug: "temazepam capsule",
        quantity: "30/30",
        altQuantity: "60/30",
        diagnosis: "insomnia",
        quantityLimitCriteria: true, 
    }, 
    {
        drug: "testosterone 1% gel packet",
        quantity: "60/30",
        diagnosis: "testicular hypofunction",
    },   
    {
        drug: "testosterone 1.62% gel pump",
        quantity: "75/30",
        diagnosis: "testicular hypofunction",
        formulary: false, 
    },   
    {
        drug: "testosterone 1.62% gel packet",
        quantity: "75/30",
        diagnosis: "testicular hypofunction",
        formulary: false, 
    },  
    {
        drug: "testosterone 10 mg gel pump",
        quantity: "60/30",
        diagnosis: "testicular hypofunction",
    },  
    {
        drug: "testosterone cypionate vial", 
        quantity: "6/84",
        diagnosis: "testicular hypofunction",
    },   
    {
        drug: "Tirosint capsule",
        quantity: "30/30",
        diagnosis: "hypothyroidism",
        formulary: false,     
    }, 
    {
        drug: "tretinoin cream",
        quantity: "45/30",
        diagnosis: "acne vulgaris",
        quantityLimitCriteria: true,     
    }, 
    {
        drug: "Trintellix tablet",
        quantity: "30/30",
        diagnosis: "major depressive disorder",
        formulary: false,     
    }, 
    {
        drug: "Trulance tablet", 
        quantity: "30/30", 
        diagnosis: "IBS-C", 
        altDiagnosis: 'chronic idiopathic constipation',
        formulary: false, 
    }, 
    {
        drug: "Trulicity pen",
        quantity: "2/28",
        diagnosis: "T2DM",
    }, 
    {
        drug: "Tryptyr eye drops", 
        quantity: "60/30", 
        diagnosis: "keratoconjunctivitis sicca", 
        formulary: false, 
    }, 
    {
        drug: "Tymlos pen",
        quantity: "1.56/30",
        diagnosis: "post-menopausal osteoporosis",
        altDiagnosis: "ostoporosis in men",
        specialty: true,
    }, 
    {
        drug: "Ubrelvy tablet",
        quantity: "16/30",
        diagnosis: "acute migraine treatment",
    },
    {
        drug: "Valtoco nasal spray", 
        quantity: "10/30",
        diagnosis: "seizures",
    },
    {
        drug: "Velphoro chewable tablet",
        quantity: "150/30",
        diagnosis: "phosphorus metabolism",
        altDiagnosis: "hyperphosphatemia", 
    }, 
    {
        drug: "Vemlidy tablet",
        quantity: "30/30",
        diagnosis: "hepatitis B",
        altDiagnosis: "HIV", 
    }, 
    {
        drug: "Venofer vial",
        quantity: "",
        diagnosis: "iron deficiency",
        formulary: false, 
    }, 
    {
        drug: "Veozah tablet", 
        quantity: "30/30",
        diagnosis: "menopausal and female climacteric states",
        formulary: false,
    },
    {
        drug: "Vevye eye drops", 
        quantity: "2/30",
        diagnosis: "dry eye syndrome",
        formulary: false,
    },
    {
        drug: "Victoza pen", 
        quantity: "9/30",
        diagnosis: "T2DM",
        formulary: false,
    },
    {
        drug: "Voquezna Dual Pak",
        quantity: "112/14",
        diagnosis: "H. pylori infection",
        altDiagnosis: "GERD", 
        formulary: false, 
    }, 
    {
        drug: "Voquezna tablet",
        quantity: "30/30",
        diagnosis: "GERD",
        formulary: false, 
    }, 
    {
        drug: "Voquezna Triple Pak",
        quantity: "112/14",
        diagnosis: "H. pylori infection",
        altDiagnosis: "GERD", 
        formulary: false, 
    }, 
    {
        drug: "voriconazole tablet", 
        quantity: "10/30",
        diagnosis: "aspergillosis",
        altDiagnosis: "febrile neutropenia",
    },
    {
        drug: "Vraylar capsule",
        quantity: "30/30",
        diagnosis: "bipolar disorder",
        altDiagnosis: "major depressive disorder", 
        formulary: false, 
    }, 
    {
        drug: "Vtama cream",
        quantity: "60/30",
        diagnosis: "atopic dermatitis",
        altDiagnosis: "psoriasis", 
        formulary: false, 
    }, 
    {
        drug: "Vyvanse capsule",
        quantity: "30/30",
        diagnosis: "ADHD",
        formulary: false,
    },  
    {
        drug: "Vyzulta eye drops",
        quantity: "2.5/30",
        diagnosis: "open-angle glaucoma",
        formulary: false,
    },  
    {
        drug: "Wegovy pen",
        quantity: "2/28",
        diagnosis: "obesity",
        altDiagnosis: "NASH",
        formulary: false, 
    }, 
    {
        drug: "Wegovy pen HD",
        quantity: "3/28",
        diagnosis: "obesity",
        formulary: false, 
    }, 
    {
        drug: "Winlevi cream", 
        quantity: "60/30",
        diagnosis: "acne vulgaris",
        formulary: false, 
    },
    {
        drug: "Wegovy tablet",
        quantity: "30/30",
        diagnosis: "obesity",
        altDiagnosis: "ASCVD", 
        formulary: false,
    }, 
    {
        drug: "Xcopri tablet",
        quantity: "30/30",
        diagnosis: "partial seizures",
        formulary: false, 
    }, 
    {
        drug: "Xcopri titration pack",
        quantity: "30/30",
        diagnosis: "partial seizures",
        formulary: false, 
    }, 
    {
        drug: "Xdemvy eye drops",
        quantity: "10/42",
        diagnosis: "infestation by Demodex mites",
    }, 
    {
        drug: "Xhance nasal spray",
        quantity: "16/30",
        diagnosis: "allergic rhinitis",
        formulary: false,
    }, 
    {
        drug: "Xifaxan tablet",
        quantity: "42/14",
        diagnosis: "irritable bowel syndrome-diarrhea",
        altDiagnosis: "SIBO",
    }, 
    {
        drug: "Xphozah tablet",
        quantity: "60/30",
        diagnosis: "hyperphosphatemia",
        altDiagnosis: "end-stage renal disease",
        formulary: false,
    }, 
    {
        drug: "Xyosted inj",
        quantity: "2/28",
        diagnosis: "testicular hypofunction",
        formulary: false, 
    }, 
    {
        drug: "Ycanth solution",
        quantity: "2/21",
        diagnosis: "molluscum contagiosum",
        formulary: false, 
    }, 
    {
        drug: "Zavzpret",
        quantity: "6/30",
        diagnosis: "acute migraine treatment",
        formulary: false, 
    }, 
    {
        drug: "Zepbound pen",
        quantity: "2/28",
        diagnosis: "OSA",
        altDiagnosis: "obesity",
        formulary: false,
    }, 

    /*{
        drug: "Zepbound KwikPen",
        quantity: "2.4/28",
        diagnosis: "OSA",
        altDiagnosis: "obesity",
        formulary: false,
    }, */
    {
        drug: "Zelsuvmi 10.3% gel",
        quantity: "31/30",
        diagnosis: "molloscum contagiosum",
        formulary: false,
    }, 
    {
        drug: "Zenpep DR capsule",
        quantity: "300/30",
        diagnosis: "exocrine pancreatic insufficiency",
        altDiagnosis: "chronic pancreatitis",
    }, 
    {
        drug: "Zoryve cream",
        quantity: "30/30",
        diagnosis: "atopic dermatitis",
        altDiagnosis: "psoriasis",
        formulary: false,
    }, 
    {
        drug: "Zoryve foam",
        quantity: "30/30",
        diagnosis: "atopic dermatitis",
        altDiagnosis: "seborrheic dermatitis",
        formulary: false,
    }, 
]